#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
def sum_even_fibonacci(max = 4000000)
    return 0 if max <= 1
    return 2 if max == 2
    sum = 2
    num1 = 1
    num2 = 2 
    next_num = num1 + num2
    loop do next_num < max
        sum += next_num if next_num % 2 == 0  
        num1 = num2
        num2 = next_num
        next_num = num1 + num2
        break if next_num >= max
    end
    return sum
end


puts sum_even_fibonacci()

# Need to find a more 'ruby - esque' way to do this..

