require 'rspec/core/rake_task'

task :default => :spec

task :play do
    ruby "lib/connect_four.rb"
end

desc "run tests for connect_four"

RSpec::Core::RakeTask.new(:spec) do |task|
    task.rspec_opts = "-c -w"
    task.verbose = false
end
