# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 582dfaa7204ea02c258f8ac0aac024a1e029f69a228b8d1fd4bcb8d6bce6f959598de139a60775aed154f561278ddaf5bfba3227620f9e20b7ef9fcc129c910f

test:
  secret_key_base: a5323e01a513206d3036ae79409d81d203e33b92409f56b7331b882cf9826d97e505433590618c2922e78dffcd23979cf1a452451cce1e3db233a2cb02baa23c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
