---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 2972820920-wxm6ZjFUyvfcjOQuXS7iLlvbKcj8CkJvEgPPOfT
:access_token_secret: vwEydKj8hPUlMRSl8eBAHAcWuVwW7SJCdVRv14Fx1VKps
